config/routes.rb
Rails.application.routes.draw do  
  root "pictures#index"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show, :edit, :update] do
    collection do
      post :confirm
    end
  end

  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :favorites, only: [:index, :create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}

  validates :email, presence: true, length: {maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation {email.downcase!}

  has_secure_password
  validates :password, length: {minimum: 6}

  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture

  mount_uploader :profile_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorite_pictures
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to request.referer, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to request.referer, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :it_is_your_post?, only: [:edit, :update, :destroy]
  
  def index
    @pictures = Picture.all
    # @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        PostPictureMailer.post_picture_mail(@picture).deliver
        redirect_to pictures_path, notice: "投稿でけた👍"
      else
        render :new
      end
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    @url = request.referer
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "You could edit now🙆"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"消せた(´ω｀)b"
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def it_is_your_post?
    redirect_to pictures_path unless @picture.user_id == current_user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :confirm]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :are_you_current_user?, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        redirect_to user_path(@user.id)
      else
        render :new
      end
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "Editing done"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image, :profile_image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def are_you_current_user?
    redirect_to user_path(@user.id) unless @user.id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_pictures_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_users_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_users_path
    elsif action_name == 'edit'
      user_path
    end
  end
end

app/views/favorites/index.html.erb
<h1>My favorite posts!!</h1>

<table>
  <tr>
    <th>Poster</th>
    <th>    </th>
    <th>Image</th>
    <th>Content</th>
  </tr>
  <% @favorites.each do |favorite| %>
    <tr>
      <td><%= image_tag(favorite.user.profile_image.icon.url) if favorite.user.profile_image && favorite.user.profile_image.icon.url %></td>
      <td><%= favorite.user.name %></td>
      <td><%= image_tag(favorite.image.thumb.url) if favorite.image && favorite.image.url %></td>
      <td><%= favorite.content %></td>
      <td><%= link_to 'confirm', picture_path(favorite.id) %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "Back to my page", user_path(current_user.id) %>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstanceGlamorous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <header>
        <h2>Instance</h2><h2>Glamorous</h2>
      </header>
      <div>
        <% if logged_in? %>
          <%= link_to "Profile", user_path(current_user.id) %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
      <br>
      <div>
        <% flash.each do |key, value| %>
          <h3><%= content_tag(:div, value, class: "#{key}") %><h3>
        <% end %>

        <%= yield %>
      </div>
      <br>
      <br>
      <footer>
        <%= link_to "インスタンスグラマラス TOP", pictures_path %>
      </footer>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_pictures_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Please select image" %>
    <%= image_tag(picture.image.thumb.url) if picture.image && picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
    <br>
    <br>
    <%= form.label :Content %>
    <%= form.text_area :content %>
  </div>
  <br>
  <% if @picture.id.present? %>
    <%= form.submit :"Could you edit?" %>
  <% else %>
    <%= form.submit :"Go post!" %>
  <% end %>
  <br>
<% end %>

app/views/pictures/confirm.html.erb
<h3>間違えとらん？</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |f| %>
  <%= image_tag(@picture.image.thumb.url) if @picture.image && @picture.image.url %>
  <%= f.hidden_field :image_cache %>
  <p>一言:<%= @picture.content %></p>
  <%= f.hidden_field :content %>
  <%= f.submit "Perfect!" %>
  <%= f.submit "Rewrite", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h2>Edit Edit!</h2>
<%= render 'form', picture: @picture %>

app/views/pictures/index.html.erb
<h1>New posts!!</h1>

<table>
  <tr>
    <th>Poster</th>
    <th>    </th>
    <th>Image</th>
    <th>Content</th>
  </tr>
  <% @pictures.each do |picture| %>
    <tr>
      <td><%= image_tag(picture.user.profile_image.icon.url) if picture.user.profile_image && picture.user.profile_image.icon.url %></td>
      <td><%= picture.user.name %></td>
      <td><%= image_tag(picture.image.thumb.url) if picture.image && picture.image.url %></td>
      <td><%= picture.content %></td>
      <td><%= link_to 'confirm', picture_path(picture.id) %></td>
      <% if picture.user_id == current_user.id %>
        <td><%= link_to 'edit', edit_picture_path(picture.id) %></td>
        <td><%= link_to 'delete', picture_path(picture.id), method: :delete, data: {confirm: '本当に消して良かですか？(>_<)'} %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "Let's post just time you !", new_picture_path %>
<br>
<%= link_to "Go to my page", user_path(current_user.id) %>
<br>
<br>

app/views/pictures/new.html.erb
<h2>Let's post</h2>
<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<h3>Post details</h3>

<br>
<p>Contributor: <%= @picture.user.name %></p>
<br>
<p>image: <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
<br>
<p>comment: <%= @picture.content %></p>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <td><%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %></td>
  <% else %>
    <td><%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %></td>
  <% end %>
<% end %>
<br>
<br>
<%= link_to 'Back page?', @url %>
<br>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: choose_users_new_or_edit) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this<%= @user.name %> f being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :"new icon" %>
    <%= image_tag(user.profile_image.icon.url) if user.profile_image && user.profile_image.url %>
    <%= f.file_field :profile_image %>
    <%= f.hidden_field :profile_image_cache %>

    <%= f.label :"new name" %>
    <%= f.text_field :name %>

    <%= f.label :"new email" %>
    <%= f.email_field :email %>

    <%= f.label :"new password" %>
    <%= f.password_field :password %>

    <%= f.label :"new password_confirmation" %>
    <%= f.password_field :password_confirmation %>

    <% if @user.id.present? %>
      <%= f.submit :"Could you edit it?" %>
    <% else %>
      <%= f.submit "Create my account" %>
    <% end %>
  </div>
<% end %>

app/views/users/confirm.html.erb
<h3>"Are there any mistakes?"</h3>
<%= form_with(model: @user, url: users_path, local: true) do |f| %>
  <p>icon image:<%= image_tag(@user.profile_image.icon.url) if @user.profile_image && @user.profile_image.icon.url %></p>
  <%= f.hidden_field :profile_image_cache %>
  <p>user name:<%= @user.name %></p>
  <%= f.hidden_field :name %>
  <p>user email:<%= @user.email %></p>
  <%= f.hidden_field :email %>
  <p>user password:<%= @user.password %></p>
  <%= f.hidden_field :password %>
  <%= f.hidden_field :password_confirmation %>
  <%= f.submit "Perfect!" %>
  <%= f.submit "I will rewrite it!", name: "back" %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit profile</h2>
<%= render 'form', user: @user %>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%= image_tag(@user.profile_image.icon.url) if @user.profile_image && @user.profile_image.icon.url %>  <%= @user.name %></h1>
<%= form_with(model: @user, url: users_path, local: true) do |f| %>
  <%= f.hidden_field :profile_image_cache %>
  <br>
  <br>
  <p>user email:<%= @user.email %></p>
<% end %>
<br>
<td><%= link_to 'My favorites', favorites_path if @user.id == current_user.id %></td>
<br>
<br>
<%= link_to 'Edit your profile', edit_user_path(@user.id) %>